version: '3.8'

services:
  smartevent.api:
    image: smartevent-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - AuthSettings__SecretKey=${JWT_KEY}
      - AuthSettings__Expires=${JWT_EXPIRES}