services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartevent-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:latest
    container_name: smartevent-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: smartevent-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://root:secret@mongodb:27017/
      #- ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongodb
  
  seq:
    image: datalust/seq:latest
    container_name: seq_logger
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: unless-stopped

  smartevent.api:
    image: smartevent-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AuthSettings__SecretKey=${JWT_KEY}
      - AuthSettings__Expires=${JWT_EXPIRES}
    depends_on:
      - rabbitmq
      - mongodb

volumes:
  mongo_data:
  rabbitmq_data:
  seq_date: